<?php

defined('BASEPATH') or exit('No direct script access allowed');

class Inventory extends AdminController
{
    public function __construct()
    {
        parent::__construct();

        if (!is_staff_logged_in()) {
            access_denied('OmniPOS Inventory');
        }

        $this->load->model('invoice_items_model');
    }

    public function index()
    {
        $data['title'] = 'OmniPOS Inventory';
        $data['warehouses'] = $this->db->where('is_active', 1)->order_by('name', 'ASC')->get(db_prefix() . 'pos_warehouses')->result_array();
        $data['items'] = $this->invoice_items_model->get();
        $data['purchase_orders'] = $this->db->order_by('id', 'DESC')->limit(100)->get(db_prefix() . 'pos_purchase_orders')->result_array();
        $data['ledger'] = $this->db->order_by('id', 'DESC')->limit(200)->get(db_prefix() . 'pos_inventory_ledger')->result_array();

        $this->load->view('omnipos/inventory/index', $data);
    }

    public function add_warehouse()
    {
        $name = trim((string) $this->input->post('name', true));
        $code = strtoupper(trim((string) $this->input->post('code', true)));

        if ($name === '' || $code === '') {
            set_alert('warning', 'Warehouse name and code are required.');
            redirect(admin_url('omnipos/inventory'));
        }

        $exists = $this->db->where('code', $code)->count_all_results(db_prefix() . 'pos_warehouses') > 0;
        if ($exists) {
            set_alert('warning', 'Warehouse code already exists.');
            redirect(admin_url('omnipos/inventory'));
        }

        $this->db->insert(db_prefix() . 'pos_warehouses', [
            'name' => $name,
            'code' => $code,
            'is_active' => 1,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);

        set_alert('success', 'Warehouse created successfully.');
        redirect(admin_url('omnipos/inventory'));
    }

    public function seed_samples()
    {
        $warehouseId = (int) $this->input->post('warehouse_id');
        if ($warehouseId < 1) {
            $warehouseId = 1;
        }

        $groupId = $this->ensure_sample_group();

        $samples = [
            ['name' => 'Demo Espresso', 'price' => 3.50, 'qty' => 120],
            ['name' => 'Demo Cappuccino', 'price' => 4.50, 'qty' => 95],
            ['name' => 'Demo Blueberry Muffin', 'price' => 2.75, 'qty' => 140],
            ['name' => 'Demo Turkey Sandwich', 'price' => 6.25, 'qty' => 80],
            ['name' => 'Demo Sparkling Water', 'price' => 1.95, 'qty' => 200],
        ];

        foreach ($samples as $sample) {
            $existing = $this->db
                ->where('description', $sample['name'])
                ->get(db_prefix() . 'items')
                ->row_array();

            if ($existing) {
                $itemId = (int) $existing['id'];
            } else {
                $this->db->insert(db_prefix() . 'items', [
                    'description' => $sample['name'],
                    'long_description' => 'Sample product generated by OmniPOS inventory seeder',
                    'rate' => $sample['price'],
                    'tax' => null,
                    'tax2' => null,
                    'group_id' => $groupId,
                    'unit' => 'pcs',
                ]);
                $itemId = (int) $this->db->insert_id();
            }

            $stock = $this->db
                ->where('warehouse_id', $warehouseId)
                ->where('item_id', $itemId)
                ->get(db_prefix() . 'pos_storeroom_stock')
                ->row_array();

            if ($stock) {
                $newQty = (float) $stock['qty_on_hand'] + (float) $sample['qty'];
                $this->db->where('id', $stock['id']);
                $this->db->update(db_prefix() . 'pos_storeroom_stock', [
                    'qty_on_hand' => $newQty,
                    'updated_at' => date('Y-m-d H:i:s'),
                ]);
            } else {
                $newQty = (float) $sample['qty'];
                $this->db->insert(db_prefix() . 'pos_storeroom_stock', [
                    'warehouse_id' => $warehouseId,
                    'item_id' => $itemId,
                    'group_id' => $groupId,
                    'qty_on_hand' => $newQty,
                    'reorder_level' => 0,
                    'updated_at' => date('Y-m-d H:i:s'),
                ]);
            }

            $this->insert_ledger($warehouseId, null, $itemId, 'seed_sample', $sample['qty'], $newQty, 'sample_seed', 'sample', 0, 'Seeded sample product with default pricing.');
        }

        set_alert('success', 'Sample products, pricing, and stock were seeded successfully.');
        redirect(admin_url('omnipos/inventory'));
    }

    public function create_purchase_order()
    {
        $warehouseId = (int) $this->input->post('warehouse_id');
        $supplier = trim((string) $this->input->post('supplier_name', true));
        $reference = trim((string) $this->input->post('reference_no', true));
        $expectedAt = trim((string) $this->input->post('expected_at', true));
        $itemId = (int) $this->input->post('item_id');
        $expectedQty = max(0, (float) $this->input->post('expected_qty'));
        $unitCost = max(0, (float) $this->input->post('unit_cost'));

        if ($warehouseId < 1 || $supplier === '' || $reference === '' || $itemId < 1 || $expectedQty <= 0) {
            set_alert('warning', 'Warehouse, supplier, reference, item, and expected quantity are required.');
            redirect(admin_url('omnipos/inventory'));
        }

        $this->db->insert(db_prefix() . 'pos_purchase_orders', [
            'warehouse_id' => $warehouseId,
            'supplier_name' => $supplier,
            'reference_no' => $reference,
            'status' => 'draft',
            'expected_at' => $expectedAt !== '' ? $expectedAt : null,
            'notes' => null,
            'created_by' => get_staff_user_id(),
            'created_at' => date('Y-m-d H:i:s'),
        ]);

        $poId = (int) $this->db->insert_id();

        $this->db->insert(db_prefix() . 'pos_purchase_order_items', [
            'purchase_order_id' => $poId,
            'item_id' => $itemId,
            'expected_qty' => $expectedQty,
            'received_qty' => 0,
            'unit_cost' => $unitCost,
        ]);

        set_alert('success', 'Purchase order created.');
        redirect(admin_url('omnipos/inventory'));
    }

    public function receive_purchase_order($poId)
    {
        $poId = (int) $poId;
        $receivedQty = max(0, (float) $this->input->post('received_qty'));

        $po = $this->db->where('id', $poId)->get(db_prefix() . 'pos_purchase_orders')->row_array();
        if (!$po) {
            set_alert('warning', 'Purchase order not found.');
            redirect(admin_url('omnipos/inventory'));
        }

        $line = $this->db->where('purchase_order_id', $poId)->get(db_prefix() . 'pos_purchase_order_items')->row_array();
        if (!$line) {
            set_alert('warning', 'Purchase order line not found.');
            redirect(admin_url('omnipos/inventory'));
        }

        if ($receivedQty <= 0) {
            set_alert('warning', 'Received quantity must be greater than zero.');
            redirect(admin_url('omnipos/inventory'));
        }

        $stock = $this->db
            ->where('warehouse_id', $po['warehouse_id'])
            ->where('item_id', $line['item_id'])
            ->get(db_prefix() . 'pos_storeroom_stock')
            ->row_array();

        if ($stock) {
            $newQty = (float) $stock['qty_on_hand'] + $receivedQty;
            $this->db->where('id', $stock['id']);
            $this->db->update(db_prefix() . 'pos_storeroom_stock', [
                'qty_on_hand' => $newQty,
                'updated_at' => date('Y-m-d H:i:s'),
            ]);
        } else {
            $item = $this->db->where('id', $line['item_id'])->get(db_prefix() . 'items')->row_array();
            $newQty = $receivedQty;
            $this->db->insert(db_prefix() . 'pos_storeroom_stock', [
                'warehouse_id' => (int) $po['warehouse_id'],
                'item_id' => (int) $line['item_id'],
                'group_id' => isset($item['group_id']) ? (int) $item['group_id'] : 0,
                'qty_on_hand' => $newQty,
                'reorder_level' => 0,
                'updated_at' => date('Y-m-d H:i:s'),
            ]);
        }

        $this->db->where('id', $line['id']);
        $this->db->update(db_prefix() . 'pos_purchase_order_items', [
            'received_qty' => (float) $line['received_qty'] + $receivedQty,
        ]);

        $this->db->where('id', $po['id']);
        $this->db->update(db_prefix() . 'pos_purchase_orders', [
            'status' => 'received',
            'received_at' => date('Y-m-d H:i:s'),
        ]);

        $this->insert_ledger((int) $po['warehouse_id'], null, (int) $line['item_id'], 'po_receive', $receivedQty, $newQty, 'po_receive', 'purchase_order', $poId, 'Inbound receiving terminal posted stock.');

        set_alert('success', 'PO received and stock updated.');
        redirect(admin_url('omnipos/inventory'));
    }

    public function transfer_stock()
    {
        $sourceWarehouse = (int) $this->input->post('source_warehouse_id');
        $destinationWarehouse = (int) $this->input->post('destination_warehouse_id');
        $itemId = (int) $this->input->post('item_id');
        $qty = max(0, (float) $this->input->post('qty'));

        if ($sourceWarehouse < 1 || $destinationWarehouse < 1 || $sourceWarehouse === $destinationWarehouse || $itemId < 1 || $qty <= 0) {
            set_alert('warning', 'Valid source, destination, item, and quantity are required.');
            redirect(admin_url('omnipos/inventory'));
        }

        $source = $this->db
            ->where('warehouse_id', $sourceWarehouse)
            ->where('item_id', $itemId)
            ->get(db_prefix() . 'pos_storeroom_stock')
            ->row_array();

        if (!$source || (float) $source['qty_on_hand'] < $qty) {
            set_alert('warning', 'Insufficient source stock for transfer.');
            redirect(admin_url('omnipos/inventory'));
        }

        $dest = $this->db
            ->where('warehouse_id', $destinationWarehouse)
            ->where('item_id', $itemId)
            ->get(db_prefix() . 'pos_storeroom_stock')
            ->row_array();

        $newSourceQty = (float) $source['qty_on_hand'] - $qty;

        $this->db->where('id', $source['id']);
        $this->db->update(db_prefix() . 'pos_storeroom_stock', [
            'qty_on_hand' => $newSourceQty,
            'updated_at' => date('Y-m-d H:i:s'),
        ]);

        if ($dest) {
            $newDestQty = (float) $dest['qty_on_hand'] + $qty;
            $this->db->where('id', $dest['id']);
            $this->db->update(db_prefix() . 'pos_storeroom_stock', [
                'qty_on_hand' => $newDestQty,
                'updated_at' => date('Y-m-d H:i:s'),
            ]);
        } else {
            $item = $this->db->where('id', $itemId)->get(db_prefix() . 'items')->row_array();
            $newDestQty = $qty;
            $this->db->insert(db_prefix() . 'pos_storeroom_stock', [
                'warehouse_id' => $destinationWarehouse,
                'item_id' => $itemId,
                'group_id' => isset($item['group_id']) ? (int) $item['group_id'] : 0,
                'qty_on_hand' => $newDestQty,
                'reorder_level' => 0,
                'updated_at' => date('Y-m-d H:i:s'),
            ]);
        }

        $this->insert_ledger($sourceWarehouse, $destinationWarehouse, $itemId, 'transfer_out', -$qty, $newSourceQty, 'transfer', 'transfer', 0, 'Balanced relocation transfer out.');
        $this->insert_ledger($destinationWarehouse, $sourceWarehouse, $itemId, 'transfer_in', $qty, $newDestQty, 'transfer', 'transfer', 0, 'Balanced relocation transfer in.');

        set_alert('success', 'Stock transferred successfully.');
        redirect(admin_url('omnipos/inventory'));
    }

    public function log_shrinkage()
    {
        $warehouseId = (int) $this->input->post('warehouse_id');
        $itemId = (int) $this->input->post('item_id');
        $qty = max(0, (float) $this->input->post('qty'));
        $reasonCode = strtoupper(trim((string) $this->input->post('reason_code', true)));
        $notes = trim((string) $this->input->post('notes', true));

        if ($warehouseId < 1 || $itemId < 1 || $qty <= 0 || $reasonCode === '') {
            set_alert('warning', 'Warehouse, item, qty, and reason code are required.');
            redirect(admin_url('omnipos/inventory'));
        }

        $stock = $this->db
            ->where('warehouse_id', $warehouseId)
            ->where('item_id', $itemId)
            ->get(db_prefix() . 'pos_storeroom_stock')
            ->row_array();

        if (!$stock || (float) $stock['qty_on_hand'] < $qty) {
            set_alert('warning', 'Insufficient stock to log shrinkage.');
            redirect(admin_url('omnipos/inventory'));
        }

        $newQty = (float) $stock['qty_on_hand'] - $qty;

        $this->db->where('id', $stock['id']);
        $this->db->update(db_prefix() . 'pos_storeroom_stock', [
            'qty_on_hand' => $newQty,
            'updated_at' => date('Y-m-d H:i:s'),
        ]);

        $this->insert_ledger($warehouseId, null, $itemId, 'write_off', -$qty, $newQty, $reasonCode, 'shrinkage', 0, $notes !== '' ? $notes : 'Inventory shrinkage/loss logger entry.');

        set_alert('success', 'Shrinkage logged successfully.');
        redirect(admin_url('omnipos/inventory'));
    }

    private function ensure_sample_group()
    {
        $group = $this->db->where('name', 'OmniPOS Samples')->get(db_prefix() . 'items_groups')->row_array();
        if ($group) {
            return (int) $group['id'];
        }

        $this->db->insert(db_prefix() . 'items_groups', ['name' => 'OmniPOS Samples']);

        return (int) $this->db->insert_id();
    }

    private function insert_ledger($warehouseId, $toWarehouseId, $itemId, $entryType, $qtyChange, $qtyAfter, $reasonCode, $refType, $refId, $notes)
    {
        $this->db->insert(db_prefix() . 'pos_inventory_ledger', [
            'warehouse_id' => $warehouseId,
            'to_warehouse_id' => $toWarehouseId,
            'item_id' => $itemId,
            'entry_type' => $entryType,
            'qty_change' => $qtyChange,
            'qty_after' => $qtyAfter,
            'reason_code' => $reasonCode,
            'reference_type' => $refType,
            'reference_id' => $refId,
            'notes' => $notes,
            'created_by' => get_staff_user_id(),
            'created_at' => date('Y-m-d H:i:s'),
        ]);
    }
}
